### ISSUE TITLE
[joss review] issues with examples

### ISSUE THREAD

**Issue by hbaniecki** [pudu-py/pudu#1]
related to https://github.com/openjournals/joss-reviews/issues/5873
1. Examples in documentation should show outputs of the executed code, e.g. plots, could also use more description to guide users
2. Examples require data which is available in the repository (not clearly stated)
3. Example 1: Wrong code? No grouping in line 80
4. Example 3: wrong path `mnist_class.h5`
5. Example 4: the rainbow colour palette is not a good option for visualising feature importance
6. Example 5: error in imports `import perturbation as ptn`
7. Example 6: missing model `load_model('data/0_526_model_(80;79).h5')`
8. Example 7: wrong path `mnist_class.h5`
9. Running examples requires new package dependencies -- Installing them could be added as an option, e.g. with `pip install pudu[examples]`

**Comment by enricgrau** [comment]
@hbaniecki Thank you for pointing out all these issues. 
1. We have improved this section by adding the output images and more context to each example.
2. We now explicitly state at the beginning of the section that data has to be downloaded.
3. The example was fixed.
4. The path is fixed.
5. We have changed the `jet` palette.
6. Import fixed.
7. The model is now included in the repository.
8. Path fixed.
9. We now include an `examples_requierments.txt` in the `examples` folder, indicating that these additional libraries can be installed from there. We can change this approach if you suggest otherwise.

**Comment by hbaniecki** [comment]
lgtm
